name: "Update the README Workflow status"
author: "Girish V"
description: "Updates the Readme with the latest workflow status using docker"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "https://github.com/GirishCodeAlchemy/GirishCodeAlchemy/blob/48e9c133950e09d23ae5b11b0ee40d41add0a507/logo.jpg"
  color: "red"
inputs:
  email:
    description: The Commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The Commiter's Name
    required: true
    default: ${{ github.actor }}
